# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05671ad1616103eb3dff7d17f44893af7779e3ae8f69e4594cf2be7f886dc24c382a3e83ea9cdf39720cba616652e1cb7260e3ea1e5c7a389c5be4025d97ee3e

test:
  secret_key_base: 06119d415c98faccedad17a88f587c05952e1b4e3955914bd2214976d8c27b7b72e3202b7a8d5f0d5021f2335e3b8f8e52ffe740c09ea4bf5d29822f3d08aed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
